server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://47.92.124.9:3306/u8-sy?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
#    password: u8123456
    password: fhaeWwcHzsCdHHHm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
